"""cascade-all feature

Revision ID: 70b913d7f98e
Revises: fab203115bc9
Create Date: 2024-11-15 07:06:09.367188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b913d7f98e'
down_revision = 'fab203115bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('asset_allocated_to_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['allocated_to'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asset_allocated_to_fkey', 'users', ['allocated_to'], ['id'])

    # ### end Alembic commands ###
