"""new column

Revision ID: 7fffaff50e67
Revises: 
Create Date: 2024-11-19 17:48:45.593504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fffaff50e67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
